import type { Article, Tool, Topic } from '@ns/shared';

const placeholder = '/media-placeholder.svg';

const tools: Tool[] = [
  {
    id: 'cursor',
    name: 'Cursor',
    description: '面向开发者的 AI 编程工具，适合代码补全、重构和项目理解。',
    fullDescription: 'Cursor 将编辑器、代码上下文和 AI 对话放在同一个工作流中，适合用来写代码、读代码、生成测试和整理重构方案。',
    domain: 'dev',
    tags: ['编程', '代码生成', '开发效率'],
    rating: 4.8,
    usageCount: '12800',
    imageUrl: placeholder,
    url: 'https://cursor.sh',
    isFavorite: false,
    verification: 'official',
    screenshots: [placeholder],
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'AI 图像生成工具，适合视觉灵感、概念图和封面探索。',
    fullDescription: 'Midjourney 擅长生成高质量视觉图像，可用于创意方向探索、品牌气质参考和内容封面草案。',
    domain: 'creative',
    tags: ['图像生成', '设计', '创意'],
    rating: 4.7,
    usageCount: '9600',
    imageUrl: placeholder,
    url: 'https://midjourney.com',
    isFavorite: false,
    verification: 'official',
    screenshots: [placeholder],
  },
  {
    id: 'gamma',
    name: 'Gamma',
    description: '用 AI 快速生成演示文稿和网页式文档。',
    fullDescription: 'Gamma 适合把提纲快速变成结构清晰的演示内容，适用于汇报、课程展示和方案说明。',
    domain: 'work',
    tags: ['PPT', '演示', '办公'],
    rating: 4.5,
    usageCount: '7200',
    imageUrl: placeholder,
    url: 'https://gamma.app',
    isFavorite: false,
    verification: 'verified',
    screenshots: [placeholder],
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: '适合在笔记、项目文档和知识库里做整理与改写。',
    fullDescription: 'Notion AI 可以帮助总结会议纪要、改写文案、梳理任务和补全文档，适合团队知识管理。',
    domain: 'work',
    tags: ['笔记', '知识库', '写作'],
    rating: 4.4,
    usageCount: '6800',
    imageUrl: placeholder,
    url: 'https://www.notion.so/product/ai',
    isFavorite: false,
    verification: 'verified',
    screenshots: [placeholder],
  },
];

const topics: Topic[] = [
  {
    id: 'ai-presentation-workflow',
    title: 'AI 演示文稿工作流',
    description: '从资料整理、提纲生成到视觉优化，完成一套可复用的汇报流程。',
    coverUrl: placeholder,
    domain: 'work',
    articleCount: 2,
    rating: 4.6,
    verification: 'verified',
  },
  {
    id: 'ai-coding-starter',
    title: 'AI 编程入门路径',
    description: '用 AI 辅助理解项目、生成测试和修复常见问题。',
    coverUrl: placeholder,
    domain: 'dev',
    articleCount: 2,
    rating: 4.7,
    verification: 'verified',
  },
  {
    id: 'creative-image-playbook',
    title: 'AI 视觉创意手册',
    description: '用图像生成工具快速验证封面、海报和风格方向。',
    coverUrl: placeholder,
    domain: 'creative',
    articleCount: 1,
    rating: 4.5,
    verification: 'community',
  },
];

const articles: Article[] = [
  {
    id: 'cursor-code-review',
    topicId: 'ai-coding-starter',
    title: '用 Cursor 做一次小型代码审查',
    summary: '把报错、相关文件和验收标准放进同一个上下文，让 AI 先定位风险再给修改建议。',
    content: '# 用 Cursor 做一次小型代码审查\n\n先限定审查范围，再让 AI 输出风险、证据和建议改法。修改后必须运行类型检查和相关测试。',
    domain: 'dev',
    author: '盘根编辑',
    authorLevel: 'certified',
    date: '2026-05-20T00:00:00.000Z',
    readTime: '5 分钟',
    relatedToolId: 'cursor',
    imageUrl: placeholder,
    isVideo: false,
    isFeatured: true,
    stats: { views: 1200, likes: 86, comments: 12 },
    verification: 'verified',
  },
  {
    id: 'gamma-presentation-outline',
    topicId: 'ai-presentation-workflow',
    title: '用 Gamma 把提纲变成汇报初稿',
    summary: '先写清听众、目标和页面结构，再让 Gamma 生成可编辑初稿。',
    content: '# 用 Gamma 把提纲变成汇报初稿\n\n推荐先准备 5 到 7 个核心页面标题，再补充每页的证据、案例和结论。',
    domain: 'work',
    author: '盘根编辑',
    authorLevel: 'certified',
    date: '2026-05-20T00:00:00.000Z',
    readTime: '4 分钟',
    relatedToolId: 'gamma',
    imageUrl: placeholder,
    isVideo: false,
    isFeatured: true,
    stats: { views: 980, likes: 64, comments: 8 },
    verification: 'verified',
  },
  {
    id: 'midjourney-cover-brief',
    topicId: 'creative-image-playbook',
    title: '给 Midjourney 写封面提示词的基本方法',
    summary: '把主体、场景、镜头、光线和用途写清楚，比堆形容词更稳定。',
    content: '# 给 Midjourney 写封面提示词的基本方法\n\n先确定主体和用途，再补充构图、材质、光线和参考风格。每次只改一个变量。',
    domain: 'creative',
    author: '盘根编辑',
    authorLevel: 'certified',
    date: '2026-05-20T00:00:00.000Z',
    readTime: '6 分钟',
    relatedToolId: 'midjourney',
    imageUrl: placeholder,
    isVideo: false,
    isFeatured: false,
    stats: { views: 860, likes: 51, comments: 6 },
    verification: 'community',
  },
];

function clone<T>(value: T): T {
  return structuredClone(value);
}

export const offlineCompassContent = {
  listTools: () => ({ items: clone(tools) }),
  listTopics: () => ({ items: clone(topics) }),
  listArticles: () => ({ items: clone(articles) }),
  getTool: (id: string) => clone(tools.find((item) => item.id === id) ?? null),
  getTopic: (id: string) => clone(topics.find((item) => item.id === id) ?? null),
  getArticle: (id: string) => clone(articles.find((item) => item.id === id) ?? null),
  search: (query: string) => {
    const needle = query.trim().toLowerCase();
    const match = (value: string) => !needle || value.toLowerCase().includes(needle);
    return {
      tools: clone(tools.filter((item) => match(`${item.name} ${item.description} ${item.tags.join(' ')}`))),
      topics: clone(topics.filter((item) => match(`${item.title} ${item.description}`))),
      articles: clone(articles.filter((item) => match(`${item.title} ${item.summary} ${item.content}`))),
      news: [],
    };
  },
};
